2022-02-21 19:18:48,363 INFO    MainThread:24200 [wandb_setup.py:_flush():71] setting env: {}
2022-02-21 19:18:48,364 INFO    MainThread:24200 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-21 19:18:48,364 INFO    MainThread:24200 [wandb_init.py:_log_setup():371] Logging user logs to /Users/stefan/Documents/Studium/CogSci in Osnabrück/Mehr/HiWi-Tätigkeiten/NBP/Content/Head2EyeMovement/Head2Eye/wandb/run-20220221_191848-1qpza2r4/logs/debug.log
2022-02-21 19:18:48,364 INFO    MainThread:24200 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/stefan/Documents/Studium/CogSci in Osnabrück/Mehr/HiWi-Tätigkeiten/NBP/Content/Head2EyeMovement/Head2Eye/wandb/run-20220221_191848-1qpza2r4/logs/debug-internal.log
2022-02-21 19:18:48,365 INFO    MainThread:24200 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f8f99dd19d0>
2022-02-21 19:18:48,365 INFO    MainThread:24200 [wandb_init.py:init():404] calling init triggers
2022-02-21 19:18:48,365 INFO    MainThread:24200 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-21 19:18:48,365 INFO    MainThread:24200 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 23up121f
2022-02-21 19:18:48,367 INFO    MainThread:24200 [wandb_run.py:finish():1457] finishing run sballe/Head2Eye/23up121f
2022-02-21 19:18:48,368 INFO    MainThread:24200 [jupyter.py:save_history():429] not saving jupyter history
2022-02-21 19:18:48,368 INFO    MainThread:24200 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-21 19:18:48,369 INFO    MainThread:24200 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-21 19:18:48,369 INFO    MainThread:24200 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-21 19:18:48,370 INFO    MainThread:24200 [wandb_run.py:_restore():1752] restore
2022-02-21 19:18:48,950 INFO    MainThread:24200 [wandb_run.py:_restore():1752] restore
2022-02-21 19:18:48,966 ERROR   MainThread:24200 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/stefan/opt/anaconda3/envs/Body2Eye/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-02-21 19:18:53,795 INFO    MainThread:24200 [wandb_setup.py:_flush():71] setting env: {}
2022-02-21 19:18:53,796 INFO    MainThread:24200 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-21 19:18:53,796 INFO    MainThread:24200 [wandb_init.py:_log_setup():371] Logging user logs to /Users/stefan/Documents/Studium/CogSci in Osnabrück/Mehr/HiWi-Tätigkeiten/NBP/Content/Head2EyeMovement/Head2Eye/wandb/run-20220221_191853-3uprz8e6/logs/debug.log
2022-02-21 19:18:53,796 INFO    MainThread:24200 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/stefan/Documents/Studium/CogSci in Osnabrück/Mehr/HiWi-Tätigkeiten/NBP/Content/Head2EyeMovement/Head2Eye/wandb/run-20220221_191853-3uprz8e6/logs/debug-internal.log
2022-02-21 19:18:53,797 INFO    MainThread:24200 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f8f89e87790>
2022-02-21 19:18:53,797 INFO    MainThread:24200 [wandb_init.py:init():404] calling init triggers
2022-02-21 19:18:53,797 INFO    MainThread:24200 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-21 19:18:53,797 INFO    MainThread:24200 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 23up121f
2022-02-21 19:18:53,798 INFO    MainThread:24200 [wandb_run.py:finish():1457] finishing run sballe/Head2Eye/23up121f
2022-02-21 19:18:53,799 INFO    MainThread:24200 [jupyter.py:save_history():429] not saving jupyter history
2022-02-21 19:18:53,800 INFO    MainThread:24200 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-21 19:18:53,800 INFO    MainThread:24200 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-21 19:18:53,801 INFO    MainThread:24200 [wandb_init.py:init():460] starting backend
2022-02-21 19:18:53,802 INFO    MainThread:24200 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-02-21 19:18:53,806 INFO    MainThread:24200 [backend.py:ensure_launched():216] starting backend process...
2022-02-21 19:18:53,820 INFO    MainThread:24200 [backend.py:ensure_launched():221] started backend process with pid: 24998
2022-02-21 19:18:53,825 INFO    MainThread:24200 [wandb_init.py:init():469] backend started and connected
2022-02-21 19:18:53,871 INFO    MainThread:24200 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-21 19:18:53,885 INFO    MainThread:24200 [wandb_init.py:init():533] updated telemetry
2022-02-21 19:18:53,937 INFO    MainThread:24200 [wandb_init.py:init():563] communicating current version
2022-02-21 19:18:55,686 INFO    MainThread:24200 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-21 19:18:55,690 INFO    MainThread:24200 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-21 19:18:55,899 INFO    MainThread:24200 [wandb_init.py:init():606] starting run threads in backend
2022-02-21 19:19:00,907 INFO    MainThread:24200 [wandb_run.py:_console_start():1810] atexit reg
2022-02-21 19:19:00,914 INFO    MainThread:24200 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-21 19:19:00,914 INFO    MainThread:24200 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-21 19:19:00,933 INFO    MainThread:24200 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-21 19:19:00,933 INFO    MainThread:24200 [wandb_init.py:init():633] run started, returning control to user process
2022-02-21 19:53:31,223 INFO    MainThread:24200 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-21 19:53:31,230 INFO    MainThread:24200 [wandb_run.py:_restore():1752] restore
2022-02-21 19:53:31,732 INFO    MainThread:24200 [wandb_run.py:_restore():1752] restore
